apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: {{ .Values.carSimulator.name }}
    app.kubernetes.io/part-of: {{ .Values.appName }}
  name: {{ .Values.carSimulator.name }}
spec:
  replicas: {{ .Values.carSimulator.replicas }}
  revisionHistoryLimit: 10
  selector:
    deploymentConfig: {{ .Values.carSimulator.name }}
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ .Values.carSimulator.name }}
        deploymentConfig: {{ .Values.carSimulator.name }}
      name: {{ .Values.carSimulator.name }}
    spec:
      volumes:
        - name: config
          configMap:
            name: {{ .Values.carSimulator.name }}-config
            defaultMode: 420
      containers:
      - name: {{ .Values.carSimulator.name }}
        image: quay.io/bobbycar/car-simulator:1.1.1
        imagePullPolicy: Always
        volumeMounts:
            - name: config
              readOnly: true
              mountPath: /opt/routes
        env:
            - name: com.redhat.bobbycar.carsim.route
              value: '/opt/routes'
            - name: com.redhat.bobbycar.carsim.cars
              value: {{ .Values.carSimulator.config.carsimCars | quote }}
            - name: com.redhat.bobbycar.carsim.factor
              value: {{ .Values.carSimulator.config.carsimFactor | quote }}
            - name: com.redhat.bobbycar.carsim.repeat
              value: {{ .Values.carSimulator.config.carsimRepeat | quote }}
            - name: quarkus.log.level
              value: 'INFO'
            - name: com.redhat.bobbycar.carsim.delay
              value: {{ .Values.carSimulator.config.carsimDelay | quote }}
            - name: mp.messaging.incoming.zonechange.type
              value: 'smallrye-mqtt'
            - name: mp.messaging.incoming.zonechange.topic
              value: {{ .Values.mqtt.topic.mqttZoneChangeTopic | quote }}
            - name: mp.messaging.incoming.zonechange.host
              value: 'bobbycar-amq-mqtt-all-0-svc'
            - name: mp.messaging.incoming.zonechange.port
              value: '61616'
            - name: com.redhat.bobbycar.carsim.datagrid.url
              value: 'http://cache-service-{{ .Values.namespace }}.{{ .Values.ocpDomain }}'
            - name: com.redhat.bobbycar.carsim.kafka.url
              value: 'http://bobbycar-{{ .Values.namespace }}.{{ .Values.ocpDomain }}'
            - name: mp.messaging.outgoing.enginemetrics.type
              value: 'smallrye-mqtt'
            - name: mp.messaging.outgoing.enginemetrics.topic
              value: {{ .Values.mqtt.topic.mqttMetricsTopic | quote }}
            - name: mp.messaging.outgoing.enginemetrics.host
              value: 'bobbycar-amq-mqtt-all-0-svc'
            - name: mp.messaging.outgoing.enginemetrics.port
              value: '61616'
            - name: mp.messaging.incoming.ota-updates.host
              value: 'bobbycar-amq-mqtt-all-0-svc'
            - name: mp.messaging.incoming.ota-updates.port
              value: '61616'
            - name: mp.messaging.incoming.ota-updates.topic
              value: 'ota/+'
            - name: mp.messaging.incoming.ota-updates.type
              value: 'smallrye-mqtt'
            - name: quarkus.http.cors
              value: 'true'
        ports:
          - containerPort: 8080
            name: http
            protocol: TCP
        envFrom:
          - configMapRef: 
              name: {{ .Values.carSimulator.name }}-config
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
    - type: ConfigChange
